name: TFF fix

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  format:
   runs-on: ubuntu-latest
   name: Check terraform files are formatted correctly

   steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.TFF }}

    - name: terraform fmt
      uses: dflook/terraform-fmt@v1.25.1

    - name: terraform fmt commit
      uses: stefanzweifel/git-auto-commit-action@v4.14.1
      with:
        commit_message: terraform fmt